### ISSUE TITLE
Gradle sync issues after importing into Android Studio

### ISSUE THREAD

**Issue by alizehctl** [udacity/ud839_ViewPager_Example#3]
Android Studio throws up gradle sync issues immediately after first importing this project.

![image](https://user-images.githubusercontent.com/31581044/57005765-0e712880-6bf4-11e9-98a9-76fd3e62c5ee.png)

These are the errors that show up after installing the suggested build tools and uprading the plugin version:

![image](https://user-images.githubusercontent.com/31581044/57005819-7de71800-6bf4-11e9-95bc-1791f920750e.png)

![image](https://user-images.githubusercontent.com/31581044/57005833-8fc8bb00-6bf4-11e9-8047-c90554169b0a.png)

I've also tried deleting the 'gradle' folder and then importing into Android Studio, and it didn't resolve the errors.

**Comment by Darkthunder119** [comment]
For anyone having similar issues in the future, I have run into this problem so many times now that I can definitively suggest how to fix this. Do the following:

After you import the project into Android studio, Open the Project Structure dialog. For the Android Gradle Plugin Version and Gradle Version, set it to the latest available on your Android Studio Installation. At the time of typing, it is 3.5.0 and 5.4.1 respectively. Then, open up the Project level build.gradle file and add this code under allprojects>repositories:

`maven {
            url 'https://maven.google.com/'
            name 'Google'
        }`

Do a sync again and there will be no errors whatsoever. There may be some warnings for the compile and testCompile configs being dated but you can ignore these as implementation and testImplementation are not really needed for what you are doing here.

**Comment by david-randoll** [comment]
Along with Darkthunder119 answer, I would like to add that the Gradle plugin version and Gradle version can be found at File>Project Structure>Project.

The latest Gradle version can be found at https://developer.android.com/studio/releases/gradle-plugin.

Also, make sure your build.gradle file has this:
buildscript {
    repositories {
        jcenter()
        google()
    }

allprojects {
    repositories {
        google()
        jcenter()
    }
}

**Comment by FTW-Khushal** [comment]
just do what android studio says
Like in first image it's say "Failed to find build tools revision"
just click on like below the error that says install build 23.2.2.....
it's works for me, i hope also work for you.........  : )

**Comment by gkraft63** [comment]
If I paid for these classes I would be pissed! Four year old projects that are outdated on the systems running now! I tried all of the above and just get new cascading errors...

**Comment by david-randoll** [comment]
> If I paid for these classes I would be pissed! Four year old projects that are outdated on the systems running now! I tried all of the above and just get new cascading errors...

Hi gkraft63, on my GitHub, I fix the Gradle issue. Do note that as time goes on this may get outdated. What I would recommend doing is look at the changes I made in the commit so that you can know how to fix any Gradle issue next time.

**Comment by gkraft63** [comment]
> 
> 
> > If I paid for these classes I would be pissed! Four year old projects that are outdated on the systems running now! I tried all of the above and just get new cascading errors...
> 
> Hi gkraft63, on my GitHub, I fix the Gradle issue. Do note that as time goes on this may get outdated. What I would recommend doing is look at the changes I made in the commit so that you can know how to fix any Gradle issue next time.

Yes I finally got it after about 4 hours work.  Its very frustrating because you want to get to the lesson, and your then sidetracked with issues like this that takes up hours of tinkering.  I did it by a fresh unziped of the project. Just updating according to the errors but then adding this ( google entry)  which I found on another site to the Gradle file:

repositories {

        jcenter()
        maven { url "https://maven.google.com" }
    }

the one from DarkThunder above gave me errors.

Thanks for your reply. I thought this thread was dead also lol.

**Comment by david-randoll** [comment]
> > > If I paid for these classes I would be pissed! Four year old projects that are outdated on the systems running now! I tried all of the above and just get new cascading errors...
> > 
> > 
> > Hi gkraft63, on my GitHub, I fix the Gradle issue. Do note that as time goes on this may get outdated. What I would recommend doing is look at the changes I made in the commit so that you can know how to fix any Gradle issue next time.
> 
> Yes I finally got it after about 4 hours work. Its very frustrating because you want to get to the lesson, and your then sidetracked with issues like this that takes up hours of tinkering. I did it by a fresh unziped of the project. Just updating according to the errors but then adding this ( google entry) which I found on another site to the Gradle file:
> 
> repositories {
> 
> ```
>     jcenter()
>     maven { url "https://maven.google.com" }
> }
> ```
> 
> the one from DarkThunder above gave me errors.
> 
> Thanks for your reply. I thought this thread was dead also lol.

Yes, I know you had to put the google entry in the build.gradle file that's why in my first comment I said that so that anyone with the same issue can resolve the gradle issue by doing that (adding just google() also works).
You have to know that there will be gradle issue everytime Google makes an update. Could be a week or a month after the gradle will get outdated again. Android studio in most cases is smart enough to resolve gradle issue but if it can't now you know what to do.

**Comment by gkraft63** [comment]
Finished the whole project, but get an app crash on startup with the bonus lesson incorporating the tab layout in the main activity. Probably something that is outdated in the code. 
Sent from Yahoo Mail on Android 
 
  On Fri, Feb 28, 2020 at 11:21 PM, d-randoll<notifications@github.com> wrote:   

If I paid for these classes I would be pissed! Four year old projects that are outdated on the systems running now! I tried all of the above and just get new cascading errors...


Hi gkraft63, on my GitHub, I fix the Gradle issue. Do note that as time goes on this may get outdated. What I would recommend doing is look at the changes I made in the commit so that you can know how to fix any Gradle issue next time.

**Comment by WD80** [comment]
Quick solution recap:

1. Import project (fresh from zip file)
2. Update project (just let Android Studio do it for you - popup right bottom should ask you) - The latest Gradle version can be found at [https://developer.android.com/studio/releases/gradle-plugin](https://developer.android.com/studio/releases/gradle-plugin).
3. In the build.gradle file at PROJECT level, make sure as per @d-randoll 's comments that you have both jcenter() and google() listed under repositories in both buildscript {} and allprojects {} (google was missing in one of those for me)

![image](https://user-images.githubusercontent.com/10477083/79733797-f1969f00-82f5-11ea-9260-bbef7f235464.png)

That should do the trick. Thanks everyone for making this work.

**Comment by Mazin1989** [comment]
For everyone who has an issue, please **copy and paste** the below code in your `gradle.build` file:

````
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven { url "https://maven.google.com" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven { url "https://maven.google.com" }
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
````

Then update your project as required by the latest changes done in the gradle file and it should work.

Hope this helps many of you who are stuck here due to this issue. (It took 10 minutes to get it to download all required components to allow the application to work and be able to install it on my phone)

**Comment by SudKul** [comment]
We have upgraded the repo to AndroidX in a recent [commit](https://github.com/udacity/ud839_ViewPager_Example/commit/60bc07c95843e4ca74f67e066a798a2ab16d8f2f). 

For further issues, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
